In [64]:
# !pip install pandas

In [65]:
import pandas as pd
import numpy as np

In [66]:
from pandas import Series, DataFrame
list_data = range(1, 6)
list_name = ['a', 'b', 'c', 'd', 'e',]
example_obj = Series(data=list_data, index=list_name)
print(example_obj)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [67]:
example_obj.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [68]:
example_obj.values # 넘파이 배열 타입

array([1, 2, 3, 4, 5])

In [69]:
example_obj.dtype

dtype('int64')

In [70]:
# 시리즈 객체의 이름 변경하기
example_obj.name = 'number'

In [71]:
example_obj

a    1
b    2
c    3
d    4
e    5
Name: number, dtype: int64

In [72]:
# 인덱스 이름 변경하기
example_obj.index.name ='id'

In [73]:
example_obj

id
a    1
b    2
c    3
d    4
e    5
Name: number, dtype: int64

In [74]:
# 시리즈 객체 생성하기
dic_data = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5} # 딕셔너리 생성
example_obj = Series(dic_data, dtype=np.int32, name='example_data')

In [75]:
example_obj

a    1
b    2
c    3
d    4
e    5
Name: example_data, dtype: int32

In [87]:
# 표 형식으로 데이터 출력
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [88]:
frame = pd.DataFrame(data) # Dataframe 생성

In [89]:
frame # 출력

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [91]:
frame.head() # 공백 = 5개 출력

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [93]:
frame.head(3)  # 3개 출력

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [95]:
frame.tail() # 뒤에서부터 역순으로 가져오기

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [96]:
frame.tail(2)

state  year  pop
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [98]:
# coulumn 에서 순서를 바꾸기
pd.DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [99]:
# column 추가하기
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt']) # 컬럼만 추가되고 데이터 값은 none으로 들어간다
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [100]:
# frame2의 컬럼 이름 확인
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [101]:
# 특정 컬럼에 접근하기
frame2.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [102]:
frame2['year']

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [103]:
# 행과 열에 접근 
# loc 와 iloc를 이용한 특정 행 접근
frame2.loc[1] # 1행

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [104]:
frame2.iloc[2] # 2행

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [107]:
# 데이터 값 넣기
frame2['debt'] = 16.5
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [112]:
frame2['debt'] = np.arange(6.) # 0 ~ 5까지 실수로 표기
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [115]:
# index 확인
frame2.index

RangeIndex(start=0, stop=6, step=1)

In [131]:
# Series를 사용하여 특정 인덱스에만 값을 설정하기
val = pd.Series([-1.2, -1.5, -1.7], index = [2, 4, 5])
val

2   -1.2
4   -1.5
5   -1.7
dtype: float64

In [132]:
frame2['debt'] = val # debt 컬럼에 val 할당
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

In [135]:
# 'state' 값이 'Ohio'인지 판단하여 새로운 'eastern' 컬럼 생성
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.2     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9  -1.5    False
5  2003  Nevada  3.2  -1.7    False

In [136]:
# 컬럼 삭제
del frame2['eastern']
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

In [137]:
# frame2의 컬럼 확인
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [138]:
# 멀티 인덱스 데이터 생성
# 딕셔너리로 멀티 인덱스를 가진 DataFrame을 생성하고 출력해보자
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [139]:
# 전치 행렬 (행과 열을 바꾸기)
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [142]:
# 특정 인덱스에 맞춰 DataFrame 생성
pd.DataFrame(populations, index = [2001, 2002, 2003]) # 2003은 데이터가 없으므로 NaN 출력

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [144]:
pdata = {'Ohio' : frame3['Ohio'][:-1], # Ohio의 마지막 값 제외
         'Nevada': frame3['Nevada'][:2]} #Nevada의 0~1값
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [148]:
frame3.index.name = 'year'
frame3

Ohio  Nevada
year              
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [149]:
frame3.columns.name = 'state'
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [150]:
# numpy로 변환
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [151]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.2],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

### 5.1.3 Index 객체 : Series 및 인덱스
- index 객체는 축 레이블(행 인덱스, 열 이름)과 기타 메타데이터를 저장
- Series 또는 DataFrame 생성 시 사용되는 레이블 배열을 내부적으로 Index 로 변환됨
- Index 객체는 불변 객체이므로 수정 할 수 없음
- index 객체는 데이터 구조 간에 공유하여 사용해도 안전
- index 객체는 배열과 유사하게 동작하며 고정 크기의 세트처럼 사용 할 수 있음
- index는 중복 된 레이블을 포함할 수 있음
- index 객체는 다양한 집합 연산 메서드를 제공

In [152]:
# Series 객체를 생성하고, index 객체를 사용하여 Series 생성
# Series 객체 생성 및 인덱스 확인
obj = pd.Series(np.arange(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [154]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [156]:
index[1:]

Index(['b', 'c'], dtype='object')

In [160]:
# 새로운 인덱스 객체를 생성
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [162]:
obj2 = pd.Series([1.5 , -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [164]:
# 인덱스 비교
obj2.index is labels # 동일
obj.index is labels # 다름

False

In [166]:
#frame3의 칼럼확인
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [168]:
'Ohio' in frame3.columns

True

In [169]:
# 2003년이 index에 포함되어 있는지 확인
2003 in frame3.index

False

In [170]:
# 중복 된 인덱스 생성가능
pd.Index(['foo', 'foo', 'bar', 'bar'])
pd.Index([0, 0, 1, 1])

Index([0, 0, 1, 1], dtype='int64')

### 5.2 핵심 기능
- reindex() 메서드를 사용하여 인덱스를 재정렬하고 결측치를 채울 수 있음
- 메서드 옵션을 사용하여 시계열 데이터와 같은 정렬된 데이터의 결측치를 보간
- DataFrame에서 행 또는 열의 인덱스를 재정렬 할 수 있고, axis 옵션을 사용하여 재정렬할 축을 지정
- drop() 메서드를 사용하여 특정 축에서 레이블을 제거
- loc와 iloc를 사용하여 레이블 또는 정수 위치를 기반으로 데이터를 선택
- [] 연산자를 사용하여 열을 선택하거나 행을 필터링 할 수 있으며 슬라이싱과 불리언 배열을 사용 할 수 있음
- loc와 iloc를 사용 할 때 슬라이싱의 endpoint가 포함됨

In [172]:
# 5.2.1 reindexing
#Series 객체 생성
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])  # obj 생성
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [175]:
# reindex를 사용하여 새로운 인덱스 설정
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [178]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [183]:
# reindex와 forward fill을 사용하여 결측값을 채우면서 시리즈의 인덱스를 변경
obj3.reindex(np.arange(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [185]:
# backward fill 뒤에 있는 값으로 채움
obj3.reindex(np.arange(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [187]:
# DataFrame 생성
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [189]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [190]:
# 특정 컬럼만 선택하여 DataFrame 재정렬, 'Ohio'는 제외

In [191]:
state = ['Texas', 'Utah', 'California']
frame.reindex(columns=state)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [192]:
frame.iloc[1:2]

Ohio  Texas  California
c     3      4           5

In [193]:
frame.reindex(state, axis='columns') 

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [194]:
frame.reindex(state, axis=1)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [195]:
# loc를 사용하여 특정 인덱스와 컬럼에 해당하는 값 선택
frame.loc[['a', 'c', 'd'],['Texas', 'California']]

Texas  California
a      1           2
c      4           5
d      7           8

### 5.2.2 하나의 행이나 열 삭제하기
- drop()

In [197]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [198]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [201]:
obj.drop(['d','c'])
#obj

a    0.0
b    1.0
e    4.0
dtype: float64

In [202]:
frame = pd.DataFrame(np.arange(16).reshape((4, 4)),
                     index=["a", "b", "c", "d"],
                     columns=["Ohio", "Texas", "California", 'Utah'])
frame

Ohio  Texas  California  Utah
a     0      1           2     3
b     4      5           6     7
c     8      9          10    11
d    12     13          14    15

In [203]:
frame.drop(index=['b', 'd'])

Ohio  Texas  California  Utah
a     0      1           2     3
c     8      9          10    11

In [204]:
frame.drop(columns=['California'])

Ohio  Texas  Utah
a     0      1     3
b     4      5     7
c     8      9    11
d    12     13    15

In [205]:
frame.drop('c', axis=0)

Ohio  Texas  California  Utah
a     0      1           2     3
b     4      5           6     7
d    12     13          14    15

In [209]:
frame.drop(['Utah', 'Texas'], axis=1)
#frame.drop(['Utah', 'Texas'], axis='columns')

Ohio  California
a     0           2
b     4           6
c     8          10
d    12          14

### 5.2.3 색인하기, 선택하기, 거르기
- loc, iloc

In [211]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [214]:
obj['b']

np.float64(1.0)

In [215]:
obj.b

np.float64(1.0)

In [217]:
obj.iloc[1]

np.float64(1.0)

In [218]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [219]:
obj[['b','d']]

b    1.0
d    3.0
dtype: float64

In [220]:
obj.iloc[[1,3]]

b    1.0
d    3.0
dtype: float64

In [222]:
obj[obj < 2] # 2보다 작은 값을 필터링하여 출력

a    0.0
b    1.0
dtype: float64

In [225]:
# loc를 사용하여 a와 c 출력
obj.loc[['a','c']]

a    0.0
c    2.0
dtype: float64

In [227]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
print(obj1)
print(obj2)

2    1
0    2
1    3
dtype: int64
a    1
b    2
c    3
dtype: int64


In [231]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [234]:
#obj2[[0, 1, 2]]
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [236]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [237]:
# loc를 사용하여 범위로 값을 선택할 떄에는 end-point가 포함됨
obj2.loc['b':'c']

b    2
c    3
dtype: int64

In [240]:
# loc을 사용하여 값 수정
obj2.loc['b':'c'] = 5 # b부터 c까지의 값을 5로 수정
obj2

a    1
b    5
c    5
dtype: int64

In [241]:
# DataFrame에서 loc와 iloc로 선택하기
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [245]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [246]:
data[['one', 'three']]

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [247]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [249]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [250]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [251]:
# 조건에 맞는 데이터를 필터링 할 때 사용
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [252]:
data[data < 5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [253]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [255]:
data.loc['Colorado']

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [256]:
data.loc[['Colorado', 'Utah']]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11

In [257]:
data.loc['Colorado',['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [258]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [262]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [263]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [264]:
data.iloc[[1, 2], [3, 1, 2]]

four  two  three
Colorado     7    5      6
Utah        11    9     10

In [265]:
# loc를 이용해 특정 범위를 선택하여 출력
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [270]:
data.iloc[: , :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [279]:
# 'three' 값이 2 이상인 행 선택
data.iloc[:, :][data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [280]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [281]:
data.loc[:, :'three'][data.three >=2]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [282]:
# loc 레이블, iloc 정수

### Chained indexing의 함정
- 데이터프레임의 값을 변경 할 때 연속적인 인덱싱을 사용하면 에러가 발생할 수 있음
- loc를 사용하여 한번에 값을 할당하는 것이 좋음

In [283]:
data.loc[:, 'one'] =1
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [285]:
data.iloc[2] = 5
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [288]:
# 특정 조건에 맞는 값 수정
# four 컬럼 값이 5보다 큰 행을 3으로 수정
data.loc[data['four'] > 5] = 3
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [296]:
# data.loc[data.three == 6]['three'] = 5 #SettingWithCopyWarning
# Try using .loc[row_indexer,col_indexer] = value instead
# data

C:\Users\402\AppData\Local\Temp\ipykernel_9772\3961975196.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data.three == 6]['three'] = 5


one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        6    6      6     6
New York    3    3      3     3

In [303]:
# three값이 5 인 행의 three 값을 6으로 수정
data.loc[data.three == 5, 'three'] = 6
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

### 5.2.4 산술 연산 및 데이터 정렬
- pandas는 인덱스가 다른 객체 간의 연산을 간단하게 처리
- Series 또는 DataFrame을 더할 때 인덱스가 일치하지 않으면 결과에 결측치가 포함
- DataFrame 의 경우 행과 열 모두에서 정렬이 발생
- fill_value 옵션을 사용하여 결측치를 특정 값으로 채울 수 있음
- 산술 메서드 (add, sub, floordiv, mul...)이름 앞에 r을 붙이면 인수의 순서를 바꿀 수 있음
- reindex() 메서드에서도 fill_value 옵션을 사용할 수 있음

In [304]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
print(s1)
print()
print(s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


In [306]:
s1 + s2 # 두 Series 객체 더하기

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [307]:
# 두 개의 DataFrame 더하기
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])  # df1 생성
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])  # df2 생성
print(df1)
print()
print(df2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0


In [308]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [311]:
df1 = pd.DataFrame({'A' : [1, 2]})
df2 = pd.DataFrame({'B' : [3, 4]})
print(df1)
print()
print(df2)

   A
0  1
1  2

   B
0  3
1  4


In [313]:
df1 + df2 # 두 DataFrame의 열이 일치하지 않으면 NaN 처리

A   B
0 NaN NaN
1 NaN NaN

In [315]:
df1.add(df2, fill_value=0) # NaN 값을 0으로 채워서 더하기

A    B
0  1.0  3.0
1  2.0  4.0

In [318]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))
df2.loc[1, 'b'] = np.nan # 'b'컬럼의 1행에 NaN값을 넣어줌
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [320]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [321]:
df1.add(df2)

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [322]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [323]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [325]:
df1.rdiv(1) # 1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [331]:
# df1의 칼럼을 df2의 칼럼에 맞추어 리인덱싱하고 NaN의 값을 0으로 출력
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### DataFrame 과 Series 간의 연산
- DataFrame과 Series 간의 연산은 NumPy 배열과 유사하게 브로드캐스팅됨.
- 기본적으로 Series의 인덱스를 DataFrame의 컬럼에 맞추어 연산하며, 행 방향으로 브로드캐스팅됨.
- 인덱스가 일치하지 않으면 결측치가 발생.
- axis 옵션을 사용하여 브로드캐스팅 축을 변경할 수 있음

In [333]:
# 배열연산
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [334]:
arr[0]

array([0., 1., 2., 3.])

In [335]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [337]:
# DataFrame에서 Series와의 연산
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [338]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [341]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [342]:
series2 = pd.Series(np.arange(3), index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [343]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [345]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [351]:
frame.sub(series3, axis = 'index') # index 또는 0

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 5.2.5 함수 적용 및 매핑
- Numpy의 ufunc (element-wise 배열 메서드)를 판다스 객체에도 사용할 수 있음.
- apply() 메서드를 사용하여 각 열 또는 행에 함수를 적용할 수 있음
- applymap() 메서드를 사용하여 각 요소에 함수를 적용할 수 있음.
- Series에는 각 요소에 함수를 적용하는 map() 메서드가 있음

In [354]:
frame = pd.DataFrame(np.random.standard_normal((4,3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b         d         e
Utah    0.761370 -1.053426  0.684568
Ohio   -0.678113 -0.937934  0.192293
Texas  -1.499286 -0.395328 -0.470606
Oregon -1.118636 -2.073898  0.327626

In [356]:
frame['b']

Utah      0.761370
Ohio     -0.678113
Texas    -1.499286
Oregon   -1.118636
Name: b, dtype: float64

In [357]:
np.abs(frame)

b         d         e
Utah    0.761370  1.053426  0.684568
Ohio    0.678113  0.937934  0.192293
Texas   1.499286  0.395328  0.470606
Oregon  1.118636  2.073898  0.327626

In [358]:
def f1(x):
    return x.max() - x.min()

In [360]:
frame.apply(f1) # 각 열에 대해 f1함수를 적용한다.

b    2.260656
d    1.678570
e    1.155175
dtype: float64

In [362]:
frame.apply(f1, axis='columns') # 각 행에 대해 f1 함수 적용

Utah      1.814796
Ohio      1.130227
Texas     1.103958
Oregon    2.401524
dtype: float64

In [365]:
def my_format(x):
    return f'{x:.2f}' # 소수점 둘쨋 자리 까지 표시

# 요소에 함수 적용
# frame.applymap(my_format)
frame.map(my_format)

b      d      e
Utah     0.76  -1.05   0.68
Ohio    -0.68  -0.94   0.19
Texas   -1.50  -0.40  -0.47
Oregon  -1.12  -2.07   0.33

In [368]:
frame['e'].map(my_format)

Utah       0.68
Ohio       0.19
Texas     -0.47
Oregon     0.33
Name: e, dtype: object

### 5.2.6 정렬 및 순위
- sort_index() 메서드를 사용하여 인덱스 레이블을 기준으로 정렬
- sort_values() 메서드를 사용하여 값을 기준으로 정렬
- 결측치는 기본적으로 정렬 시 마지막으로 이동하지만, na_position 옵션을 사용하여 변경 할 수 있음
- DataFrame의 경우 여러 열을 기준으로 정렬
- rank() 메서드를 사용하여 순위를 계산할 수 있으며, 동점 처리방식과 오름차순/내림차순 여부를 설정 할 수 있음

In [370]:
obj = pd.Series(np.arange(4), index = ['d', 'a', 'b', 'c']) # Series 생성
obj

d    0
a    1
b    2
c    3
dtype: int64

In [371]:
# 인덱스를 기준으로 정렬
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [376]:
# 역순으로 정렬하기
obj.sort_index(ascending = False)

d    0
c    3
b    2
a    1
dtype: int64

In [377]:
# DataFrame의 인덱스 정렬
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])
frame  # frame 출력

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [379]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [382]:
frame.sort_index(axis='columns')

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [384]:
obj = pd.Series([4, np.nan, 7, np.nan, -3.2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.2
dtype: float64

In [385]:
obj.sort_values()

4   -3.2
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [387]:
obj.sort_values(na_position='first') # nan값을 앞쪽으로 보내고 정렬

1    NaN
3    NaN
4   -3.2
0    4.0
2    7.0
dtype: float64

In [388]:
# DataFrame의 값 정렬
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame  # frame 출력

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [389]:
frame.sort_values('b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [391]:
frame.sort_values(['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [400]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [401]:
obj.rank() # default 값이 낮을수록 1순위

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [402]:
obj.rank(ascending = False) # 값이 높을수록 1순위

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [404]:
obj.rank(method='first') # 동률인 경우 인덱스 순으로 순위정렬

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [405]:
# DataFrame의 열을 기준으로 순위 매기기
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
                      "c": [-2, 5, 8, -2.5]})
frame  # frame 출력

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [408]:
frame.rank(axis=1) # columns 기준으로 정렬

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### 5.2.7 중복 레이블을 가진 축 인덱스
- pandas는 중복된 축 레이블을 허용
- is_unique 속성을 사용하여 인덱스 레이블이 고유한지 여부를 확인
- 중복된 레이블로 인덱싱하면 Series를 반환하고, 고유한 레이블로 인덱싱하면 스칼라 값을 반환
- DataFrame의 경우에도 마찬가지로 동작

In [409]:
obj = pd.Series(np.arange(5), index = ['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [410]:
obj.index.is_unique

False

In [411]:
obj['a']

a    0
a    1
dtype: int64

In [413]:
obj['c']

np.int64(4)

In [415]:
df = pd.DataFrame(np.random.standard_normal((5,3)),
                  index=['a','a','b','b','c'])
df

0         1         2
a -0.105474 -1.175539 -0.496808
a  0.170929  0.027224 -0.626094
b  0.253304 -0.377600  0.049095
b  1.832365  0.633471 -0.098499
c -0.508477 -1.075957 -0.821978

In [417]:
df.loc['a']

0         1         2
a -0.105474 -1.175539 -0.496808
a  0.170929  0.027224 -0.626094

In [418]:
df.loc['c']

0   -0.508477
1   -1.075957
2   -0.821978
Name: c, dtype: float64

### 5.3 기술 통계 계산과 요약
- pandas 객체는 다양한 수학 및 통계 메서드를 제공.
- sum(), mean(), count() 와 같은 메서드는 축을 따라 요약 통계를 계산.
- skipna 옵션을 사용하여 결측치를 제외할지 여부를 지정할 수 있음.
- idxmin(), idxmax() 메서드는 최솟값 또는 최댓값이 있는 인덱스를 반환.
- cumsum() 메서드는 누적 합계를 계산.
- describe() 메서드는 여러 통계 요약을 한 번에 제공.
- 비숫자 데이터에 대한 describe() 메서드는 다른 요약 통계를 제공.

In [419]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                  index=["a", "b", "c", "d"], columns=["one", "two"])  # NaN 값이 포함된 DataFrame 생성
df  # df 출력

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [421]:
df.sum() # 각 열에 대한 합계

one    9.25
two   -5.80
dtype: float64

In [423]:
df.sum(axis=1) # 각 행에 대한 합계

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [425]:
df.sum(axis=1, skipna=False) # NaN 값을 제외 하지않음

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [427]:
df.mean(axis=1) # 각 행의 평균값 구하기

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [428]:
df.idxmax() # 각 열의 최대값을 가진 인덱스 구하기

one    b
two    d
dtype: object

In [430]:
df.cumsum() # 누적 합계

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [432]:
df.describe() # 요약 통계

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

### 5.3.1 상관 관계 및 공분산:
- 일부 요약 통계(예: 상관 관계 및 공분산)는 쌍의 인수를 사용하여 계산.
- Series의 corr 메서드는 두 Series에서 겹치는 NA가 아닌 인덱스 정렬된 값의 상관 관계를 계산.
- 관련하여 cov는 공분산을 계산.
- 반면 DataFrame의 corr 및 cov 메서드는 각각 DataFrame으로 전체 상관 관계 또는 공분산 행렬을 반환.
- DataFrame의 corrwith 메서드를 사용하면 DataFrame의 열 또는 행과 다른 Series 또는 DataFrame 간의 쌍별 상관 관계를 계산.
- 고유 값, 값 개수 및 isin(): 다른 클래스의 관련 메서드는 1차원 Series에 포함된 값에 대한 정보를 추출

In [439]:
price = pd.read_pickle('examples/yahoo_price.pkl')
volume = pd.read_pickle('examples/yahoo_volume.pkl')

price.head()

returns = price.pct_change() # 변동률 계산
returns.tail() # 뒤에서 5개 출력

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [441]:
returns['MSFT'].corr(returns['IBM']) #상관관계

np.float64(0.49976361144151155)

In [444]:
returns['MSFT'].cov(returns['IBM']) #공분산

np.float64(8.870655479703546e-05)

In [443]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [445]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [447]:
# corrwith() : 다른 Series나 DataFrame과의 상관관계 계산
returns.corrwith(returns['IBM']) # IBM과 다른 모든 종목의 상관 관계 계산

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

### 5.3.2 유일값, 값세기, 멤버쉽

In [448]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [450]:
# 유일값(고유값)
unique = obj.unique()
unique

array(['c', 'a', 'd', 'b'], dtype=object)

In [451]:
# 각 값의 빈도수를 반환
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [453]:
mask = obj.isin(['b','c']) # 'b'나 'c'가 있으면 True
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [455]:
# isin() 을 이용한 필터링
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [462]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a']) # 비교할 값
unique_val = pd.Series(['c', 'b', 'a']) # 고유 값
indices = pd.Index(unique_val).get_indexer(to_match) # 값의 위치 매칭
# Index.get_indexer : 고유하지 않은 값(비교할 값)에서 고유한 값을 가지고 있는 배열에서 인덱스를 반환
indices # c, b, a의 위치를 표시

array([0, 2, 1, 1, 0, 2])

In [463]:
# DataFrame 에서 여러 열에 대한 히스토그램 계산, value_counts() 사용
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                     "Qu2": [2, 3, 1, 2, 3],
                     "Qu3": [1, 5, 2, 4, 4]})  # DataFrame 생성
data  # data 출력

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [466]:
# Qu1 에서 값의 빈도수를 계산하고 정렬
data['Qu1'].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [467]:
data['Qu3'].value_counts().sort_index()

Qu3
1    1
2    1
4    2
5    1
Name: count, dtype: int64

In [468]:
data = pd.DataFrame({'a': [1, 1, 1, 2, 2], 'b':[0, 0, 1, 0, 0]})
data

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [469]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64